name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Update main-src
      run: |
        if git show-ref --verify --quiet refs/heads/main-src; then
          git checkout main-src
        else
          git checkout --orphan main-src
        fi

        git rm -rf . 
        cp -R src/.. 

        git add .
        git commit -m "ci: sync src/ to main-src branch"
        git push origin main-src --force

    - name: Checkout
      run: git checkout main