name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  package-src:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: src
          path: src/

  deploy-main-src:
    runs-on: ubuntu-latest
    needs: package-src

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: src
          path: src

      - name: Push to main-src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin main-src || true
          git checkout -B main-src
          git rm -rf . || true

          git commit -m "Release from ${{ github.sha }}"
          git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} main-src

  delete:
    needs:
      - deploy-main-src
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Delete Linux Artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: src