name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Update main-src
      run: |
        if git rev-parse --verify main-src; then
          git checkout main-src
        else
          git checkout --orphan main-src
        fi

        git rm -rf .

        git checkout main -- src

        rsync -av --delete src/ .

        git add .
        git commit -m "ci: sync src/ to main-src"
        git push origin main-src --force

        git checkout main

    - name: Checkout
      run: git checkout main